// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSNPfkWh8ApoWzaspT-R4LKfR9FFL9g8',
    appId: '1:962276706746:web:7e32f4f54684008dee7583',
    messagingSenderId: '962276706746',
    projectId: 'doctorplus-paciv',
    authDomain: 'doctorplus-paciv.firebaseapp.com',
    storageBucket: 'doctorplus-paciv.appspot.com',
    measurementId: 'G-CBP9MRJYLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGAvD2jOq7RN_KDRddyLxfYDQ6wMGJ_es',
    appId: '1:962276706746:android:74470a3c10f483efee7583',
    messagingSenderId: '962276706746',
    projectId: 'doctorplus-paciv',
    storageBucket: 'doctorplus-paciv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT-NUEsTjtPaAk-iFWSviIxO3X2K7Yvv4',
    appId: '1:962276706746:ios:c96d416bd7949e96ee7583',
    messagingSenderId: '962276706746',
    projectId: 'doctorplus-paciv',
    storageBucket: 'doctorplus-paciv.appspot.com',
    iosClientId: '962276706746-r6fhfsglavg5f1l5qe34cn8om2scv4p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorPlusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT-NUEsTjtPaAk-iFWSviIxO3X2K7Yvv4',
    appId: '1:962276706746:ios:c96d416bd7949e96ee7583',
    messagingSenderId: '962276706746',
    projectId: 'doctorplus-paciv',
    storageBucket: 'doctorplus-paciv.appspot.com',
    iosClientId: '962276706746-r6fhfsglavg5f1l5qe34cn8om2scv4p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorPlusApp',
  );
}
